Retry failed system allocations

diff --git a/spread.yaml b/spread.yaml
--- a/spread.yaml
+++ b/spread.yaml
@@ -40,16 +40,21 @@ backends:
           ;;
       esac
 
-      if OUT="$(image-garden allocate "${SPREAD_SYSTEM/-plus-/+}")"; then
-        if [ "$HOST_ARCH" != "$SYSTEM_ARCH" ] || [ ! -e /dev/kvm ]; then
-          # Spread has a fixed, 5-minute timeout for ssh to become ready.
-          # When emulating across architectures this may not be sufficient
-          # for the system to become ready. Sleep for a while to give things
-          # a chance to finish.
-          sleep 5m
-        fi
-        ADDRESS "$OUT"
+      image_garden_output="$(image-garden allocate "${SPREAD_SYSTEM/-plus-/+}")" || true
+
+      if [ -z "$image_garden_output" ]; then
+        ERROR "Image garden allocation failed for system: $SPREAD_SYSTEM"
       fi
+
+      if [ "$HOST_ARCH" != "$SYSTEM_ARCH" ] || [ ! -e /dev/kvm ]; then
+        # Spread has a fixed, 5-minute timeout for ssh to become ready.
+        # When emulating across architectures this may not be sufficient
+        # for the system to become ready. Sleep for a while to give things
+        # a chance to finish.
+        sleep 5m
+      fi
+
+      ADDRESS "$image_garden_output"
     discard: |
       # Spread automatically injects /snap/bin to PATH. When we are
       # running from the image-garden snap then SPREAD_HOST_PATH is the
