Add retry logic to spread tests

diff --git a/spread/main/update_policy/task.yaml b/spread/main/update_policy/task.yaml
--- a/spread/main/update_policy/task.yaml
+++ b/spread/main/update_policy/task.yaml
@@ -1,41 +1,47 @@
 summary: Test update container's restart policy
 
 execute: |
- # read docker file from stdin and build the image
- dockerfile=$(cat <<EOF
-   FROM alpine
-   CMD sleep 5; exit 1
- EOF
- )
- echo "$dockerfile" | sudo docker build -t image -
 
- # run a container which applied always restart policy
- # if the container exits with a non-zero exit status
- id=$(sudo docker run --restart always -dit image)
+  source "$SCRIPTS_PATH/common.sh"
 
- # check the restart policy
- restart_policy=$(sudo docker inspect  -f '{{.HostConfig.RestartPolicy.Name}}' $id)
- [ $restart_policy = "always" ] || exit 1
+  # read docker file from stdin and build the image
+  dockerfile=$(cat <<EOF
+    FROM alpine
+    CMD sleep 5; exit 1
+  EOF
+  )
+  echo "$dockerfile" | sudo docker build -t image -
 
- # pause processes in the container
- sudo docker pause $id
+  # run a container which applied always restart policy
+  # if the container exits with a non-zero exit status
+  id=$(sudo docker run --restart always -dit image)
 
- # update restart policy
- sudo docker update --restart=no $id
+  # check the restart policy
+  restart_policy=$(sudo docker inspect  -f '{{.HostConfig.RestartPolicy.Name}}' $id)
+  [ $restart_policy = "always" ] || exit 1
 
- # unpause processes
- sudo docker unpause $id
+  # pause processes in the container
+  sudo docker pause $id
 
- # check the restart policy
- restart_policy=$(sudo docker inspect  -f '{{.HostConfig.RestartPolicy.Name}}' $id)
- [ $restart_policy = "no" ] || exit 1
+  # update restart policy
+  sudo docker update --restart=no $id
 
- # wait a bit and check if service restarts
- sleep 10
+  # unpause processes
+  sudo docker unpause $id
 
- # check the actual restart count
- restart_count=$(sudo docker inspect -f '{{.RestartCount}}' $id)
- [ $restart_count = 0 ] || exit 1
+  # check the restart policy
+  restart_policy=$(sudo docker inspect  -f '{{.HostConfig.RestartPolicy.Name}}' $id)
+  [ $restart_policy = "no" ] || exit 1
 
- # remove the container
- sudo docker rm -f $id
+  # wait a bit and check if service restarts
+  sleep 10
+
+  function verify_restart_counter() {
+    restart_count=$(sudo docker inspect -f '{{.RestartCount}}' $id)
+    [ $restart_count = 0 ]
+  }
+
+  run_retry_command verify_restart_counter
+
+  # remove the container
+  sudo docker rm -f $id
