Nvidia support core24 (#203)
* Bump libnvidia-container and nvidia-container-toolkit to version 1.17.3

* Add initial version of support for uc24, sill alongside uc22 support

* Update comment with correct syntax regarding spec-dirs

* Switch base to core24, and remove core22 based nvidia support

* Remove provider for gpu-2404 to prevent pulling in snap as a dedendency by default

* Replace gpu-2404-wrapper with forked optional version, and disable nvidia-container-toolkit on systems which don't have any detected nvidia support

* Add core22 based nvidia support again, to support both UC24 and UC22

* fix: make sure the gpu wrapper only applies to the required ubuntu versions

* Move nvidia support detection to separate command-chain, and add some basic logging on detected status

* Move some setup logic to post-refresh only, to prevent it being run twice for no good reason

diff --git a/nvidia/nvidia-container-toolkit b/nvidia/nvidia-container-toolkit
--- a/nvidia/nvidia-container-toolkit
+++ b/nvidia/nvidia-container-toolkit
@@ -4,37 +4,27 @@ set -eu
 
 . "${SNAP}/usr/share/nvidia-container-toolkit/lib"
 
-# Just exit if NVIDIA support is disabled #
-[ "${NVIDIA_SUPPORT_DISABLED}" != "true" ] || exit 0
+[ "${NVIDIA_SUPPORT_CLASSIC}" == "true" ] && echo "Running on Classic system"
+[ "${NVIDIA_SUPPORT_CORE}" == "true" ] && echo "Running on Ubuntu Core system"
 
-NVIDIA_ENABLE="false"
+# FIXME: error here if both core and classic are detecgted ?
+# [ "${NVIDIA_SUPPORT_CLASSIC}" == "true" -a "${NVIDIA_SUPPORT_CORE}" == "true"  ]
 
-# Determine if we can enable NVIDIA support or not #
-snapctl is-connected graphics-core22 && NVIDIA_ENABLE="true"
-[ "${NVIDIA_SUPPORT_CLASSIC}" == "true" ] && NVIDIA_ENABLE="true"
-
-# Ensure nvidia support setup correctly, and only if hardware is preset and correct #
-if [ "${NVIDIA_ENABLE}" == "true" ] ; then
-
-    [ "${NVIDIA_SUPPORT_CLASSIC}" == "true" ] && echo "Running on Classic system" || echo "Running on Ubuntu Core system"
-
-    # Connection hooks are run early - copy the config file from $SNAP into $SNAP_DATA if it doesn't exist
-    if [ ! -f "$SNAP_DATA/config/daemon.json" ]; then
-        mkdir -p "$SNAP_DATA/config"
-        cp "$SNAP/config/daemon.json" "$SNAP_DATA/config/daemon.json"
-    fi
-
-    # Ensure hardware present #
-    nvidia_hw_ensure
-
-    # As service order is not guaranteed outside of snap - wait a bit for nvidia assemble to complete #
-    device_wait /dev/nvidiactl || exit 0
-    echo "NVIDIA ready"
-
-    # Ensure the data dirs exist #
-    ensure_nvidia_data_dirs
-
-    # Setup nvidia support, but do not exit on failure #
-    cdi_generate && nvidia_runtime_config && docker_runtime_configure && setup_info || setup_fail
-
+# Connection hooks are run early - copy the config file from $SNAP into $SNAP_DATA if it doesn't exist
+if [ ! -f "$SNAP_DATA/config/daemon.json" ]; then
+    mkdir -p "$SNAP_DATA/config"
+    cp "$SNAP/config/daemon.json" "$SNAP_DATA/config/daemon.json"
 fi
+
+# Ensure hardware present #
+nvidia_hw_ensure
+
+# As service order is not guaranteed outside of snap - wait a bit for nvidia assemble to complete #
+device_wait /dev/nvidiactl || exit 0
+echo "NVIDIA ready"
+
+# Ensure the data dirs exist #
+ensure_nvidia_data_dirs
+
+# Setup nvidia support, but do not exit on failure #
+cdi_generate && nvidia_runtime_config && docker_runtime_configure && setup_info || setup_fail
