ci(smoke-test): Regression test to check non-stopping container problem (#258)
* CI(smoke-test): Regression test to check non-stopping container problem

* feat: use bash container for test

* feat: add timeout for step

---------

Signed-off-by: Lincoln Wallace <lincoln.wallace@canonical.com>

diff --git a/.github/workflows/smoke-test.yml b/.github/workflows/smoke-test.yml
--- a/.github/workflows/smoke-test.yml
+++ b/.github/workflows/smoke-test.yml
@@ -179,6 +179,16 @@ jobs:
       - name: Hello World (init)
         run: sudo docker run --rm --init hello-world
 
+      # NOTE: regression test for aa default profile reload issue 
+      # see: https://github.com/canonical/docker-snap/issues/36
+      - name: Stop container
+        timeout-minutes: 1
+        run: |
+          trap 'echo "error, sad day ($?)"; sleep 1; sudo snap logs -n=20 docker.dockerd; sleep 1; sudo tail -n20 /var/log/*.log; sudo dmesg | tail -n20; sudo journalctl --no-pager | grep DENIED | grep docker' ERR
+          docker run --rm -d --name test bash bash -c 'cleanup(){ sleep 60; }; trap cleanup SIGTERM SIGINT SIGHUP SIGQUIT; while true; do sleep 1; done'
+          sleep 5
+          sudo docker stop test
+
       - name: Docker Build
         run: |
           sudo docker build --pull -t debian-hello - <<'EOF'
