feat: add checker for possible early container failure
Signed-off-by: Lincoln Wallace <lincoln.wallace@canonical.com>

diff --git a/.github/workflows/smoke-test.yml b/.github/workflows/smoke-test.yml
--- a/.github/workflows/smoke-test.yml
+++ b/.github/workflows/smoke-test.yml
@@ -123,6 +123,11 @@ jobs:
           echo "List of running containers"
           docker ps -a
 
+          if [[ -n $(sudo docker ps -q --filter "status=exited") ]]; then
+            echo "Error: docker snap did not start all containers"
+            exit 1
+          fi
+
           # NOTE: adjust this accordingly with the commands above if needed
           STARTED_CONTAINERS=6
 
